baseURL = "/"
languageCode = "en-us"
title = "ML Hub"
theme = "kube"
description = "ML Hub是一个机器学习支撑平台，提供机器学习算法开发、模型训练、版本控制和服务发布等全生命周期管理功能。"
Paginate = 4
[Params]
  RSSLink = "/index.xml"
  author = "@mlhub" # add your company name
  github = "" # add your github profile name
  twitter = "" # add your twitter profile
  email = "mlhub@njuics.cn"

[[menu.main]]
    name = "技术"
    weight = -100
    url = "/docs/"
[[menu.main]]
    name = "日志"
    weight = -100
    url = "/blog/"
[[menu.main]]
    name = "FAQ"
    weight = 100
    url = "/faq/"
